# Generated by Django 3.0.7 on 2020-07-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200608_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showimage',
            name='text',
        ),
    ]
