# Generated by Django 3.0.7 on 2020-07-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_showimage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='showimage',
            name='text',
            field=models.TextField(default='Your Perfect Eyebrows', max_length=140),
        ),
    ]
