# Generated by Django 3.0.6 on 2020-06-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showimage',
            name='text',
            field=models.TextField(default='Your Perfect Eyebrows', max_length=140),
        ),
    ]
