# Generated by Django 3.0.6 on 2020-06-08 12:16

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_showimage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showimage',
            name='image',
            field=models.ImageField(upload_to=pages.models.scrambleName, verbose_name='Uploaded Image'),
        ),
    ]
